{{ if .Values.hostExp }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-exp
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    route.openshift.io/termination: "edge"
    route.openshift.io/insecureEdgeTerminationPolicy: "Redirect"
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  {{ if .Values.ingressTlsEnabled }}
  tls:
    - hosts:
        - {{ .Values.hostExp }}
      secretName: {{ .Values.hostExp }}-tls
  {{ end }}
  rules:
    - host: {{ .Values.hostExp }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-exp
                port:
                  number: 80
{{ end }}
